In [ ]:
! pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install matplotlib torch torchaudio

In [ ]:
pip install PySoundFile

In [ ]:
pip install pydub

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download mozillaorg/common-voice

100% 12.0G/12.0G [01:51<00:00, 191MB/s]
100% 12.0G/12.0G [01:51<00:00, 116MB/s]


In [ ]:
! unzip common-voice.zip


Streaming output truncated to the last 5000 lines.
  inflating: cv-valid-train/cv-valid-train/sample-190776.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190777.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190778.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190779.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190780.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190781.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190782.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190783.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190784.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190785.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190786.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190787.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190788.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190789.mp3  
  inflating: cv-valid-train/cv-valid-train/sample-190790.mp3  
  in

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('cv-valid-train.csv')

In [ ]:
data

filename  \
0       cv-valid-train/sample-000000.mp3   
1       cv-valid-train/sample-000001.mp3   
2       cv-valid-train/sample-000002.mp3   
3       cv-valid-train/sample-000003.mp3   
4       cv-valid-train/sample-000004.mp3   
...                                  ...   
195771  cv-valid-train/sample-195771.mp3   
195772  cv-valid-train/sample-195772.mp3   
195773  cv-valid-train/sample-195773.mp3   
195774  cv-valid-train/sample-195774.mp3   
195775  cv-valid-train/sample-195775.mp3   

                                                     text  up_votes  \
0       learn to recognize omens and follow them the o...         1   
1              everything in the universe evolved he said         1   
2       you came so that you could learn about your dr...         1   
3       so now i fear nothing because it was those ome...         1   
4       if you start your emails with greetings let me...         3   
...                                                   ...       ...   
195771                        the englishman said nothing         1   
195772                       the irish man sipped his tea         1   
195773                        what do you know about that         1   
195774                 the phone rang while she was awake         2   
195775  among these people were a couple of cyclists a...         4   

        down_votes       age gender   accent  duration  
0                0       NaN    NaN      NaN       NaN  
1                0       NaN    NaN      NaN       NaN  
2                0       NaN    NaN      NaN       NaN  
3                0       NaN    NaN      NaN       NaN  
4                2       NaN    NaN      NaN       NaN  
...            ...       ...    ...      ...       ...  
195771           0  thirties   male  england       NaN  
195772           0       NaN    NaN      NaN       NaN  
195773           0       NaN    NaN      NaN       NaN  
195774           0  twenties   male       us       NaN  
195775           1       NaN    NaN      NaN       NaN  

[195776 rows x 8 columns]

In [ ]:
data.columns

Index(['filename', 'text', 'up_votes', 'down_votes', 'age', 'gender', 'accent',
       'duration'],
      dtype='object')

In [ ]:
from os import path
from pydub import AudioSegment

# files                                                                         
src = "sample-000005.mp3"
dst = "test.wav"

# convert wav to mp3                                                            
sound = AudioSegment.from_mp3(src)
sound.export(dst, format="wav")

In [ ]:
print(data['text'].head(1))

0    learn to recognize omens and follow them the o...
Name: text, dtype: object


In [ ]:
pip install pytorch-nlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 KB 9.4 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
import tensorflow 

from tensorflow import keras

In [ ]:
characters = [x for x in "abcdefghijklmnopqrstuvwxyz"]

c_to_num = keras.layers.StringLookup(vocabulary=characters, oov_token="")

In [ ]:
data = tf.constant([["a", "c", "z"], ["d", "a", "b"]])

In [ ]:
c_to_num(data)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 1,  3, 26],
       [ 4,  1,  2]])>

In [ ]:
from torchnlp.encoders import LabelEncoder

data = ["a", "c", "d", "e"]
encoder = LabelEncoder(data, reserved_labels=['unknown'], unknown_index=0, enforce_reversible=True)

enl = encoder.batch_encode(data)

print(enl)

tensor([1, 2, 3, 4])


In [ ]:
num = [1, 2, 3, 4, 3]

encoder.batch_decode(enl)

['a', 'c', 'd', 'e']

In [ ]:
file = tf.io.read_file("test.wav")
audio, _ =tf.audio.decode_wav(file)
audio = tf.squeeze(audio,axis=-1)
audio = tf.cast(audio,tf.float32)

In [ ]:
audio

<tf.Tensor: shape=(154368,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>

In [ ]:
pip install pydub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import torchaudio
import requests
import matplotlib.pyplot as plt
import pydub
from pydub import AudioSegment
import torchaudio
import io


In [ ]:
pip install ffmpeg


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6084 sha256=a0bf880ea8bf18b27d1918a6ec14cf34b724c876f34a074497e5af240f4c015a
  Stored in directory: /root/.cache/pip/wheels/30/33/46/5ab7eca55b9490dddbf3441c68a29535996270ef1ce8b9b6d7
Successfully built ffmpeg


In [ ]:
from os import path
from pydub import AudioSegment

In [ ]:
src = "./sample-000000.mp3"
dst = "test.wav"

# convert wav to mp3                                                            
sound = AudioSegment.from_mp3(src)
sound=sound.export(dst, format="wav")

In [ ]:
sound

<_io.BufferedRandom name='test.wav'>

In [ ]:
!unzip '/content/cv-valid-test.zip'


Archive:  /content/cv-valid-test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /content/cv-valid-test.zip or
        /content/cv-valid-test.zip.zip, and cannot find /content/cv-valid-test.zip.ZIP, period.


In [ ]:
#/content/cv-valid-train
#/content/cv-valid-train
# Load mp3 file
filename = "./sample-000000.mp3"
mp3_audio = AudioSegment.from_file(filename, format="mp3")


with io.BytesIO() as f:
    mp3_audio.export(f, format="wav")
    f.seek(0)
    raw_audio_data = f.read()

waveform, sample_rate = torchaudio.load(io.BytesIO(raw_audio_data))

In [ ]:
audio_file = "test.wav"

In [ ]:
waveform, sample_rate = torchaudio.load(audio_file)

In [ ]:
metadata = torchaudio.info(audio_file)
print(metadata)

AudioMetaData(sample_rate=48000, num_frames=154368, num_channels=1, bits_per_sample=16, encoding=PCM_S)


In [ ]:
torch.set_printoptions(profile="full")


In [ ]:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device {device}")
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
print(f"Sample Rate: {bundle.sample_rate}")
print(f"Labels: {bundle.get_labels()}")
model = bundle.get_model().to(device)
print(model.__class__)

In [ ]:
#waveform, sample_rate = torchaudio.load(SPEECH_FILE)
waveform, sample_rate = torchaudio.load('test.wav')
waveform = waveform.to(device)
if sample_rate != bundle.sample_rate:
    waveform = torchaudio.functional.resample(waveform, sample_rate, bundle.sample_rate)

In [ ]:
with torch.inference_mode():
    emission, _ = model(waveform)

In [ ]:
class GreedyCTCDecoder(torch.nn.Module):
    def __init__(self, labels, blank=0):
        super().__init__()
        self.labels = labels
        self.blank = blank

    def forward(self, emission: torch.Tensor) -> str:
        indices = torch.argmax(emission, dim=-1) # [num_seq,]
        indices = torch.unique_consecutive(indices, dim=-1)
        indices = [i for i in indices if i != self.blank]
        return "".join([self.labels[i] for i in indices])

In [ ]:
decoder = GreedyCTCDecoder(labels=bundle.get_labels())
transcript = decoder(emission[0])

In [ ]:
print(transcript)

In [ ]:
print(waveform)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.

In [ ]:
waveform = torch.squeeze(waveform, -1)

In [ ]:
waveform = waveform.type(torch.FloatTensor)

In [ ]:
waveform.dtype

torch.float32

In [ ]:
spectrograms = torch.stft(waveform, win_length=160, n_fft=256, hop_length=384)
spectrograms = torch.abs(spectrograms)
spectrograms = torch.pow(spectrograms,0.5)

spec_m = torch.mean(spectrograms,1,keepdim=True)
spec_m = torch.mean(spectrograms,1,keepdim=True)
spec_std = torch.std(spectrograms,1,keepdim=True)

spectrograms = (spectrograms - spec_m)/(spec_std + pow(1*10, -10))

In [ ]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
import nltk
from nltk.parse import DependencyGraph

# Input sentence
sentence = "a bedroom next to the kitchen"

# Tokenize the sentence
tokens = nltk.word_tokenize(sentence)

# POS tagging
tagged_tokens = nltk.pos_tag(tokens)
print(tagged_tokens)
# Create a dependency graph

#dep_graph = DependencyGraph(tagged_tokens)

# Extract relations between words
for node in dep_graph.nodes.values():
    if node['rel'] != 'ROOT':
        print(node['word'], '->', node['rel'], '->', dep_graph.nodes[node['head']]['word'])


[('a', 'DT'), ('bedroom', 'NN'), ('next', 'IN'), ('to', 'TO'), ('the', 'DT'), ('kitchen', 'NN')]


AttributeError: ignored

In [ ]:
import spacy
from spacy import displacy


nlp = spacy.load("en_core_web_sm")


sentence = "a bedroom next to the kitchen and a lounge next to the dining room"


doc = nlp(sentence)


displacy.render(doc, style='dep', jupyter=True, options={})


for token in doc:
    for child in token.children:
        print(token.text, "->", child.dep_, "->", child.text)

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


bedroom -> det -> a
bedroom -> advmod -> next
next -> prep -> to
to -> pobj -> kitchen
kitchen -> det -> the
kitchen -> cc -> and
kitchen -> conj -> lounge
kitchen -> advmod -> next
lounge -> det -> a
next -> prep -> to
to -> pobj -> room
room -> det -> the
room -> compound -> dining


In [ ]:
import spacy

# Load the language model
nlp = spacy.load("en_core_web_sm")

# Input sentence
sentence = "a bedroom next to the kitchen"

# Process the sentence using the language model
doc = nlp(sentence)

# Extract relations between words and parts of speech
for token in doc:
    for child in token.children:
        print(token.text, "->", token.pos_, "->", child.dep_, "->", child.text, "->", child.pos_)

bedroom -> NOUN -> det -> a -> DET
bedroom -> NOUN -> advmod -> next -> ADV
next -> ADV -> prep -> to -> ADP
to -> ADP -> pobj -> kitchen -> NOUN
kitchen -> NOUN -> det -> the -> DET
